version: "2.1"
networks:
  internal_network:
services:      
  db:
    restart: always
    networks:
      - internal_network
    image: bwaters/ambar-mongodb:latest
    build: MongoDB/.
    environment:
      - cacheSizeGB=2
    volumes:
      - ${dataPath}/db:/data/db
    expose:
      - "27017"   
  es:
    restart: always
    networks:
      - internal_network
    image: bwaters/ambar-es:latest
    build: ElasticSearch/.
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ${dataPath}/es:/usr/share/elasticsearch/data
  rabbit:
    restart: always
    networks:
      - internal_network
    image: bwaters/ambar-rabbit:latest
    build: Rabbit/.
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    volumes:
      - ${dataPath}/rabbit:/var/lib/rabbitmq
  redis:
    restart: always
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
    image: bwaters/ambar-redis:latest
    build: Redis/.
    expose:
      - "6379" 
  serviceapi:
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    image: bwaters/ambar-serviceapi:latest
    build: ServiceApi/.
    expose:
      - "8081"  
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=${langAnalyzer}   
  webapi:
    depends_on:
      serviceapi:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    image: bwaters/ambar-webapi:latest
    build: WebApi/.
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:      
      - analyticsToken=cda4b0bb11a1f32aed7564b08c455992
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit    
  frontend:
    depends_on:
      webapi:
        condition: service_healthy
    image: bwaters/ambar-frontend:latest
    build: FrontEnd/.
    restart: always
    networks:
      - internal_network
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - api=http://${ambarHostIpAddress}:8080  
  pipeline0:
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
    image: bwaters/ambar-pipeline:latest
    build: Pipeline/.
    restart: always
    networks:
      - internal_network  
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
  crawler:
    depends_on: 
      serviceapi: 
        condition: service_healthy 
    image: bwaters/ambar-local-crawler
    build: LocalCrawler/.
    restart: always
    networks:
      - internal_network
    expose:
      - "8082"
    environment:      
      - name=${crawlerName}
    volumes:
      - ${pathToCrawl}:/usr/data


  
  